id: I43A14987
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T17:33:30+00:00'
last_modified: '2022-06-08T10:12:36.449556+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24770
  title: བོད་རིག་པའི་མཁས་པ་དགེ་འདུན་ཆོས་འཕེལ་གྱི་རིག་གཞུང་བསམ་བློ་ཞིབ་འཇུག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    52A5:
      image_group_id: I1KG24772
      title: ''
      total_pages: 543
      order: 1
      base_file: 52A5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
